adminUser:
  password: vault:gargoylequill/adminUser:password
  username: admin
dashboardAuthID: vault:gargoylequill:dashboardAuthID
dashboardAuthOrg: arcalos-dashboard
dashboardAuthSecret: vault:gargoylequill:dashboardAuthSecret
dashboardGrpchost: dex.jx
enableDocker: false
pipelineUser:
  email: jenkins-x@googlegroups.com
  token: vault:gargoylequill/pipelineUser:token
  username: jenkins-x-bot-test
prow:
  hmacToken: vault:gargoylequill/prow:hmacToken
